### ISSUE TITLE
Deployment does not have minimum availability

### ISSUE THREAD

**Issue by xinmans** [jameswynn/helm-charts#14]
Pods "homepage-77cdf87bbc-" is forbidden: error looking up service account default/homepage: serviceaccount "homepage" not found:Deployment does not have minimum availability.

**Comment by xinmans** [comment]
kubectl create serviceaccount homepage
serviceaccount/homepage created

Fix this bug

**Comment by theeternalrat** [comment]
I also found this bug on a fresh deploy. Simply creating the SA fixed it like @xinmans said.

**Comment by jameswynn** [comment]
Since it seems like a misconfiguration, I'm closing this.
