### ISSUE TITLE
Selectively disable or reconfigure service health checks

### ISSUE THREAD

**Issue by june012006** [jameswynn/helm-charts#27]
To clarify what I mean, I'm currently using a combination of endpoint, ingress and service to point to non cluster resources (router, adguard home, proxmox), primarily for reverse proxying them with my kubernetes traefik instance.   Of course, I'm also using the ingress to add to homepage, however since there is no pod associated, I get "not found" on all such entries, and the logs of course show that as well in the errors.   An annotation to skip health checks, or to use an alternate method, like ping, would be helpful.

**Comment by jameswynn** [comment]
The helm chart doesn't control the annotations. That would require an enhancement in Homepage itself. That said, if you open a ticket there for it and ping me I'll take a look at it.
