### ISSUE TITLE
Auto-Bump Homepage Version?

### ISSUE THREAD

**Issue by Aesop7** [jameswynn/helm-charts#7]
Until there is an official helm repo for Homepage, it would be awesome if this unofficial repo could automatically bump versions to stay in sync with the latest upstream Homepage version.

Love the work you've done - again huge thank you @jameswynn !

**Comment by philipsens** [comment]
You could also achieve this by using an update strategy in Argo CD or Flux.

**Comment by Aesop7** [comment]
I see [it](https://github.com/jameswynn/helm-charts/blob/44549a319b8378232929f0d895f669bd4dd2c3f0/charts/homepage/values.yaml#L3C2-L3C2) now.  at first I thought that this was pulling a different docker build than the official one.  I'll close this.
